"""create initial dealflow schema

Revision ID: a054fdb05a3a
Revises:
Create Date: 2026-08-30 19:21:17.375293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision: str = "a054fdb05a3a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("primary_contact_name", sa.String(length=100), nullable=True),
        sa.Column("primary_contact_email", sa.String(length=255), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column("deleted_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("code", name=op.f("uq_customers_code")),
    )
    op.create_index("ix_customers_name", "customers", ["name"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("event_key", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="PENDING", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("available_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("published_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_events_attempts_nonnegative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        "ix_outbox_events_aggregate",
        "outbox_events",
        ["aggregate_type", "aggregate_id"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_events_status_available",
        "outbox_events",
        ["status", "available_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=32), server_default="PRESALES", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "rfps",
        sa.Column("customer_id", sa.String(length=36), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("reference_number", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="UPLOADED", nullable=False),
        sa.Column("current_stage", sa.String(length=64), server_default="uploaded", nullable=False),
        sa.Column("priority", sa.String(length=16), server_default="NORMAL", nullable=False),
        sa.Column("source_language", sa.String(length=16), nullable=True),
        sa.Column("due_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("processing_started_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("completed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column("deleted_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_rfps_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_rfps_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfps")),
        sa.UniqueConstraint(
            "customer_id", "reference_number", name="uq_rfps_customer_reference_number"
        ),
    )
    op.create_index("ix_rfps_customer_status", "rfps", ["customer_id", "status"], unique=False)
    op.create_index("ix_rfps_due_at", "rfps", ["due_at"], unique=False)
    op.create_index("ix_rfps_status_created_at", "rfps", ["status", "created_at"], unique=False)
    op.create_table(
        "documents",
        sa.Column("rfp_id", sa.String(length=36), nullable=True),
        sa.Column("uploaded_by_id", sa.String(length=36), nullable=True),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="UPLOADED", nullable=False),
        sa.Column("bucket", sa.String(length=100), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("document_version", sa.String(length=32), nullable=True),
        sa.Column("knowledge_category", sa.String(length=64), nullable=True),
        sa.Column("parsed_text_object_key", sa.String(length=512), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_documents_size_bytes_nonnegative")),
        sa.ForeignKeyConstraint(
            ["rfp_id"], ["rfps.id"], name=op.f("fk_documents_rfp_id_rfps"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("bucket", "object_key", name="uq_documents_bucket_object_key"),
    )
    op.create_index("ix_documents_checksum", "documents", ["checksum_sha256"], unique=False)
    op.create_index("ix_documents_rfp_type", "documents", ["rfp_id", "document_type"], unique=False)
    op.create_index(
        "ix_documents_type_status", "documents", ["document_type", "status"], unique=False
    )
    op.create_table(
        "workflow_runs",
        sa.Column("rfp_id", sa.String(length=36), nullable=False),
        sa.Column("run_type", sa.String(length=32), server_default="FULL", nullable=False),
        sa.Column("status", sa.String(length=32), server_default="PENDING", nullable=False),
        sa.Column("current_node", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=100), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=255), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("output_summary", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("completed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt >= 0", name=op.f("ck_workflow_runs_attempt_nonnegative")),
        sa.ForeignKeyConstraint(
            ["rfp_id"], ["rfps.id"], name=op.f("fk_workflow_runs_rfp_id_rfps"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
        sa.UniqueConstraint("correlation_id", name=op.f("uq_workflow_runs_correlation_id")),
    )
    op.create_index(
        "ix_workflow_runs_rfp_status", "workflow_runs", ["rfp_id", "status"], unique=False
    )
    op.create_index(
        "ix_workflow_runs_status_created_at",
        "workflow_runs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "proposals",
        sa.Column("rfp_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="DRAFT", nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("executive_summary", sa.Text(), nullable=True),
        sa.Column("docx_object_key", sa.String(length=512), nullable=True),
        sa.Column("pdf_object_key", sa.String(length=512), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("approved_by_id", sa.String(length=36), nullable=True),
        sa.Column("approved_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_proposals_approved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rfp_id"], ["rfps.id"], name=op.f("fk_proposals_rfp_id_rfps"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_proposals_workflow_run_id_workflow_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposals")),
        sa.UniqueConstraint("rfp_id", "version", name="uq_proposals_rfp_version"),
    )
    op.create_index("ix_proposals_rfp_status", "proposals", ["rfp_id", "status"], unique=False)
    op.create_table(
        "requirements",
        sa.Column("rfp_id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=False),
        sa.Column("parent_requirement_id", sa.String(length=36), nullable=True),
        sa.Column("requirement_key", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("requirement_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("mandatory", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("source_page_start", sa.Integer(), nullable=True),
        sa.Column("source_page_end", sa.Integer(), nullable=True),
        sa.Column("source_quote", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.Column("raw_output", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_requirements_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_requirement_id"],
            ["requirements.id"],
            name=op.f("fk_requirements_parent_requirement_id_requirements"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rfp_id"], ["rfps.id"], name=op.f("fk_requirements_rfp_id_rfps"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_requirements_source_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirements")),
        sa.UniqueConstraint("rfp_id", "requirement_key", name="uq_requirements_rfp_key"),
    )
    op.create_index("ix_requirements_fingerprint", "requirements", ["fingerprint"], unique=False)
    op.create_index(
        "ix_requirements_rfp_category", "requirements", ["rfp_id", "category"], unique=False
    )
    op.create_index(
        "ix_requirements_rfp_mandatory", "requirements", ["rfp_id", "mandatory"], unique=False
    )
    op.create_table(
        "capability_results",
        sa.Column("requirement_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("customization_notes", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("raw_output", sa.JSON(), nullable=False),
        sa.Column("reviewed_by_id", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_capability_results_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_capability_results_requirement_id_requirements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
            name=op.f("fk_capability_results_reviewed_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_capability_results_workflow_run_id_workflow_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capability_results")),
        sa.UniqueConstraint(
            "requirement_id", "workflow_run_id", name="uq_capability_results_requirement_run"
        ),
    )
    op.create_index(
        "ix_capability_results_requirement_created",
        "capability_results",
        ["requirement_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_capability_results_status", "capability_results", ["status"], unique=False)
    op.create_table(
        "proposal_reviews",
        sa.Column("proposal_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
            name=op.f("fk_proposal_reviews_proposal_id_proposals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_proposal_reviews_reviewer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_reviews")),
    )
    op.create_index(
        "ix_proposal_reviews_proposal_created",
        "proposal_reviews",
        ["proposal_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "capability_evidence",
        sa.Column("capability_result_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("qdrant_point_id", sa.String(length=100), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("retrieval_score", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("rerank_score", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("rank_position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(fsp=6),
            server_default=sa.text("CURRENT_TIMESTAMP(6)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["capability_result_id"],
            ["capability_results.id"],
            name=op.f("fk_capability_evidence_capability_result_id_capability_results"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_capability_evidence_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capability_evidence")),
        sa.UniqueConstraint(
            "capability_result_id", "qdrant_point_id", name="uq_capability_evidence_result_point"
        ),
    )
    op.create_index(
        "ix_capability_evidence_result_rank",
        "capability_evidence",
        ["capability_result_id", "rank_position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_capability_evidence_result_rank", table_name="capability_evidence")
    op.drop_table("capability_evidence")
    op.drop_index("ix_proposal_reviews_proposal_created", table_name="proposal_reviews")
    op.drop_table("proposal_reviews")
    op.drop_index("ix_capability_results_status", table_name="capability_results")
    op.drop_index("ix_capability_results_requirement_created", table_name="capability_results")
    op.drop_table("capability_results")
    op.drop_index("ix_requirements_rfp_mandatory", table_name="requirements")
    op.drop_index("ix_requirements_rfp_category", table_name="requirements")
    op.drop_index("ix_requirements_fingerprint", table_name="requirements")
    op.drop_table("requirements")
    op.drop_index("ix_proposals_rfp_status", table_name="proposals")
    op.drop_table("proposals")
    op.drop_index("ix_workflow_runs_status_created_at", table_name="workflow_runs")
    op.drop_index("ix_workflow_runs_rfp_status", table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index("ix_documents_type_status", table_name="documents")
    op.drop_index("ix_documents_rfp_type", table_name="documents")
    op.drop_index("ix_documents_checksum", table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_rfps_status_created_at", table_name="rfps")
    op.drop_index("ix_rfps_due_at", table_name="rfps")
    op.drop_index("ix_rfps_customer_status", table_name="rfps")
    op.drop_table("rfps")
    op.drop_table("users")
    op.drop_index("ix_outbox_events_status_available", table_name="outbox_events")
    op.drop_index("ix_outbox_events_aggregate", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_customers_name", table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
