from enum import StrEnum


class UserRole(StrEnum):
    ADMIN = "ADMIN"
    SALES = "SALES"
    PRESALES = "PRESALES"


class RFPStatus(StrEnum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    REVIEW_PENDING = "REVIEW_PENDING"
    APPROVED = "APPROVED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class Priority(StrEnum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"


class DocumentType(StrEnum):
    RFP_SOURCE = "RFP_SOURCE"
    RFP_ATTACHMENT = "RFP_ATTACHMENT"
    KNOWLEDGE = "KNOWLEDGE"
    PROPOSAL = "PROPOSAL"


class DocumentStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PARSING = "PARSING"
    INDEXING = "INDEXING"
    READY = "READY"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"


class WorkflowRunType(StrEnum):
    FULL = "FULL"
    REPROCESS = "REPROCESS"
    PROPOSAL_REVISION = "PROPOSAL_REVISION"


class WorkflowStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_REVIEW = "WAITING_REVIEW"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class CapabilityStatus(StrEnum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    ENTERPRISE_ONLY = "ENTERPRISE_ONLY"
    REQUIRES_CUSTOMIZATION = "REQUIRES_CUSTOMIZATION"
    NEED_REVIEW = "NEED_REVIEW"


class ProposalStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW_PENDING = "REVIEW_PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    SUPERSEDED = "SUPERSEDED"


class ReviewDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
